### PR TITLE
Wizard Panel - Dynamically change "Save" action in the Content Wizard #410

### PR DESCRIPTION
**Pull request by vbradnitski**

### CODE REVIEW

**Comment by alansemenov** [comment]
1. Default caption of the Save button is now "Saved". When I create a new content or open existing one, it's very confusing to see "Saved". It should be "Save" (like before, but without "as Draft").

2. Changes made in the Page Editor don't seem to be tracked at all. The simple rule is - if you get a notification about unsaved changes when you try to close the browser tab, then the "Save" button should be enabled:
image

**Comment by vbradnitski** [comment]
fixed

**Comment by alansemenov** [comment]
The first part is fixed, but Save still doesn't get enabled after changes done in the Page Editor.

Two simple examples:
1. Open a site and add a new part (or layout) to the page. Don't select descriptor.
or
2. Open a site with already existing components on the page and change position of one of the components using DnD.

In both cases "Save" is still disabled after the change, but if you try to close the browser tab you'll get a confirmation about unsaved changes.

**Comment by alansemenov** [comment]
Awesome job, @vbradnitski !

**Pull request merged**
