### PR TITLE
Users App - trim spaces in displayName input (Wizards) #184

### PR DESCRIPTION
**Pull request by edloidas**
Updated wizard header inputs: they will be normalized, before retrieving values from them, except the `isNew()` check.

### CODE REVIEW

**Comment by edloidas** [comment]
@ase While the text trimming definitely _can_ be the part of the `required` and `prettifyName` functions, `trimText` should still be a separate function as well. There are two main reasons behind it:
* Each such function in `common` do a small part of the job. `prettifyName`  and `trimText` may have a similar purpose, but the `required` just do a completely different thing;
* `prettifyName` just calls the `NamePrettifier.create` from that Java class;
* Some fields, like `displayName`, are not `required`. They must not be prettified also (replacing unsafe characters, replacing whitespaces with `-`, or making it lowercase). So, they must use a separate function, that will only trim the text.

**Comment by alansemenov** [comment]
From what I see in the code, displayName must be required (it is also required in the UI). It is required in ``create`` but not required in ``update``, so that looks like a bug.

Calls like ``common.trimText(common.required(params, 'key'))`` definitely look clumsy. It's also wrong that developer must always remember to add a call to ``common.trimText`` for every new value that should be trimmed. `required` method simply gets value of a required parameter, and I can't think of any case where value of required parameter should not be trimmed? If you have any examples, please tell me.

Another alterinative is to implement `requiredString` method which trims the value before sending it over to `required`.

**Comment by edloidas** [comment]
Hi, I've updated the JS server-side layer once more, moving trimming to the `required()` function from the `common` module and adding the `skipTrimming` parameter just in case.

As for the previous comment:
* Absence of `required` is not a bug. Rather its presence is excessiveness. All received params are validated in schemas: `query` or `mutation` with GraphQL types and methods, like `graphQl.nonNull`, that will check almost every param, except `description`, probably. `required` function do the same thing, throwing the exception for the `null` or `undefined` values. I would just suggest to remove it, but it would take some more time and I can't say for all the cases it's used. Maybe we should do it after the release. We don't need more unexpected bugs due to refactoring. Removing the `required` only the `trimming` function will remain, that will do just one thing. 
* Yes, I don't like the `common.trimText(common.required(...))` calls either.

**Comment by sigdestad** [comment]
Having thought about this, you are right the Java API should probably not do trimming as this could cause issues in clients I guess? However, if display names should never have whitespaces, it should at least throw an error if data is passed in with "unacceptable" format. The trimming would then naturally be implemented in the client specific interfaces.

**Comment by edloidas** [comment]
@sigdestad @alansemenov At this point, I will leave the final decision for you.

As for my thoughts:
* Throwing an error in case of untrimmed `displayName` (and other things) is not a good solution either, in my opinion. The warning may be a better solution. But still... What if the untrimmed text is the result of something went wrong on the client? The operation will just fail for the user.
* There is also a question, where we show throw that error? In application server-side JS, or in `xp/auth-lib` (`auth.js`), or in the `xp`'s Java code (handlers, node layer)?
* `xp/auth-lib` may be (already?) used in other applications. What if that app is not well tested? Or it just receives the data from another app and passes it to `xp/auth-lib`? Should we still reject requests with such data? I think not. From my experiences with using open APIs of some services, like Telegram or Yandex, or writing the libs of my own, untrimmed text is not such critical problem, that we need to throw the exception and reject the requests.

**Pull request merged**
